name: Bionic-Clang-Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  industrial_ci:
    name: Melodic
    runs-on: ubuntu-latest
    env:
      CI_NAME: Bionic-Clang-Build
      OS_NAME: ubuntu
      OS_CODE_NAME: bionic
      ROS_DISTRO: melodic
      ROS_REPO: main
      NOT_TEST_INSTALL: true
      ADDITIONAL_DEBS: "autotools-dev automake libpcre3-dev bison clang git libglu1-mesa-dev freeglut3-dev mesa-common-dev"
      CMAKE_ARGS: "-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++"
    steps:
      - uses: actions/checkout@v1

      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.CI_NAME }}/.ccache
          key: ${{ env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ env.CI_NAME }}-ccache-

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{env}}
